# Generated by Django 4.1.7 on 2023-03-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
