# Generated by Django 4.1.7 on 2023-03-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorydb',
            new_name='Category_db',
        ),
    ]
