# Generated by Django 4.1.7 on 2023-03-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_categorydb_category_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=20, null=True)),
                ('Product', models.CharField(blank=True, max_length=20, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
