# Generated by Django 4.1.7 on 2023-03-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
