# Generated by Django 4.1.7 on 2023-04-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_productdb_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productdb',
            new_name='Product_db',
        ),
    ]
