# Generated by Django 4.1.7 on 2023-03-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('Username', models.CharField(blank=True, max_length=10, null=True)),
                ('Password', models.CharField(blank=True, max_length=10, null=True)),
                ('Confirm', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
