# Generated by Django 4.1.7 on 2023-04-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_cartdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Description',
        ),
    ]
