# Generated by Django 3.2.10 on 2023-06-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_remove_cartdb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.TextField(blank=True, max_length=20, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('Postalcode', models.IntegerField(blank=True, null=True)),
                ('PhoneNumber', models.IntegerField(blank=True, null=True)),
                ('EmailId', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartdb',
            name='Image',
        ),
    ]
