# Generated by Django 3.2.10 on 2023-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20230620_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='Address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
